name: fap_attendance
description: FAP Attendance Desktop - Member 1 core modules.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  crypto: ^3.0.6
  file_picker: ^10.1.9
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  archive: ^4.2.0
  xml: ^7.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/ocr_windows.ps1
